version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /core
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /disarray
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /network
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /runtime
    schedule:
      interval: daily