version: 2
updates:
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /disarray
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /lib/core
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /lib/ledger
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /lib/minis
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /lib/network
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /lib/runtime
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /lib/sdk
    schedule:
      interval: daily