version: 2
updates:
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /disarray
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /crates/core
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /crates/ledger
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /crates/minis
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /crates/network
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /crates/runtime
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /crates/sdk
    schedule:
      interval: daily