tasks:
  - init: |
      sudo apt update -y && sudo apt upgrade -y 
      sudo apt install -y protobuf-compiler 
      rustup default nightly 
      rustup target add wasm32-unknown-unknown --toolchain nightly
      rustup component add clippy rustfmt --toolchain nightly
    command: cargo watch -x test


