tasks:
  - init: rustup default nightly && rustup component add clippy rustfmt && rustup target add wasm32-unknown-unknown wasm32-wasi && sudo apt install -y protobuf-compiler
    command: cargo watch -x test --all
