[package]
authors = ["FL03 <jo3mccain@icloud.com>", "Scattered-Systems (https://scattered-systems.com)"]
build = "build.rs"
categories = ["development-tools", "network-programming"]
description = "Disarray a hybrid multi-chain engineered as a high-preformant execution layer for our portals"
edition = "2021"
homepage = "https://github.com/scattered-systems/disarray/wiki"
keywords = ["async", "scsys"]
license = "Apache-2.0"
name = "disarray-sdk"
readme = "README.md"
repository = "https://github.com/scattered-systems/disarray"
version = "0.1.21" # TODO - Update the cargo package version

[features]
default = ["core", "ledger", "network", "runtime"]


core = []

ledger = ["disarray-ledger"]
network = ["disarray-network"]
runtime = ["disarray-runtime"]

[lib]
crate-type = ["cdylib", "rlib"]
test = true

[dev-dependencies]
scsys = { features = ["full"], version = "0.1.33" }

[build-dependencies]

[dependencies]
disarray-ledger = { features = [], optional = true, path = "../ledger", version = "0.1.21" }
disarray-network = { features = [], optional = true, path = "../network", version = "0.1.21" }
disarray-runtime = { features = [], optional = true, path = "../runtime", version = "0.1.21" }

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]
