[package]
authors = ["FL03 <jo3mccain@icloud.com>", "Scattered-Systems (https://scattered-systems.com)"]
build = "build.rs"
categories = ["development-tools", "network-programming"]
description = "Disarray a hybrid multi-chain engineered as a high-preformant execution layer for our portals"
edition = "2021"
homepage = "https://scattered-systems.github.io/disarray"
keywords = ["async", "scsys"]
license = "MIT"
name = "disarray"
readme = "README.md"
repository = "https://github.com/scattered-systems/disarray"
version = "0.1.20" # TODO - Update the cargo package version

[features]
default = ["core", "ledger", "network", "runtime"]
full = ["core", "ledger", "network", "runtime"]

core = ["disarray-core/default", "disarray-core/full"]

ledger = ["disarray-ledger"]
network = ["disarray-network"]
runtime = ["disarray-runtime"]

[lib]
crate-type = ["cdylib", "rlib"]
test = true

[dev-dependencies]

[build-dependencies]

[dependencies.disarray-core]
features = ["full"]
optional = true
path = "../core"
version = "0.1.20"

[dependencies.disarray-ledger]
optional = true
path = "../ledger"
version = "0.1.20"

[dependencies.disarray-network]
optional = true
path = "../network"
version = "0.1.20"

[dependencies.disarray-runtime]
optional = true
path = "../runtime"
version = "0.1.20"
