[package]
authors = ["FL03 <jo3mccain@icloud.com> (https://github.com/FL03)"]
categories = []
description = "Disarray is a hybrid blockchain network"
edition = "2021"
keywords = []
license = "Apache-2.0"
name = "disarray"
repository = "https://github.com/scattered-systems/disarray"
version = "0.1.21"

[build-dependencies]

[dependencies]
clap = { features = ["derive"], version = "4.0.22" }
futures = "0.3.25"
hex = "0.4.3"
opentelemetry = { features = ["rt-tokio"], version = "0.18.0" }
opentelemetry-jaeger = { features = ["full"], version = "0.17.0" }
rand = { features = [], version = "0.8.5" }
ring = { features = ["wasm32_c"], version = "0.16.20" }
scsys = { features = ["full"], version = "0.1.37" }
serde = { features = ["derive"], version = "1.0.151" }
serde_json = "1.0.91"
strum = { features = ["derive"], version = "0.24.1" }
tarpc = { features = ["full"], version = "0.31.0" }
tokio = { features = ["full"], version = "1.21.2" }
tower = "0.4.13"
tower-http = { features = ["full"], version = "0.3.4" }
tracing = "0.1.36"
tracing-opentelemetry = "0.18.0"
tracing-subscriber = { features = ["env-filter"], version = "0.3.15" }

[dependencies.disarray-sdk]
features = ["full"]
path = "../crates/sdk"
version = "0.1.21"

[dev-dependencies]
