[package]
authors = ["FL03 <jo3mccain@icloud.com>", "Scattered-Systems (https://scattered-systems.com)"]
categories = []
description = "Disarray"
edition = "2021"
homepage = "https://github.com/scattered-systems/disarray"
keywords = []
license = "MIT"
name = "disarray"
readme = "README.md"
repository = "https://github.com/scattered-systems/disarray"
version = "0.1.7" # TODO - Update the cargo package version

[features]
core = ["disarray-core"]
default = ["core", "external"]
external = ["bson/default", "bson/chrono-0_4", "bson/serde_with", "serde/derive"]
full = ["default", "derive", "macros"]
derive = ["disarray-derive"]
macros = ["disarray-macros"]

[lib]
bench = false
crate-type = ["cdylib", "rlib"]
test = true

[dependencies]
bson = { features = ["chrono-0_4", "serde_with"], version = "2.3.0" }
chrono = "0.4.19"
config = "0.13.1"
digest = "0.10.3"
glob = "0.3.0"
log = "0.4.17"
once_cell = "1.12.0"
serde = { features = ["derive"], version = "1.0.138" }

[dependencies.disarray-core]
optional = true
path = "../core"
version = ">=0.1.6"

[dependencies.disarray-derive]
optional = true
path = "../derive"
version = ">=0.1.6"

[dependencies.disarray-macros]
optional = true
path = "../macros"
version = ">=0.1.6"
