[package]
authors = ["FL03 <jo3mccain@icloud.com>", "Scattered-Systems (https://scattered-systems.com)"]
categories = ["development-tools", "network-programming"]
description = "Disarray is an all-in-one toolkit for designing optimized Ethereum Native, zk-SNARK blockchains"
edition = "2021"
homepage = "https://scattered-systems.github.io/disarray"
keywords = ["async", "scsys"]
license = "MIT"
name = "disarray-network"
repository = "https://github.com/scattered-systems/disarray"
version = "0.1.20" # TODO - Update the cargo package version

[lib]
crate-type = ["cdylib", "rlib"]
test = true

[dependencies]
digest = "0.10.3"
futures = "0.3.21"
glob = "0.3.0"
hex = "0.4.3"
hyper = { features = ["full"], version = "0.14.20" }
lazy_static = "1.4.0"
libp2p = { features = ["dns", "kad", "mdns", "mplex", "noise", "tcp", "tokio"], version = "0.49.0" }
log = "0.4.17"
once_cell = "1.15.0"
multihash = "0.16.3"
scsys = { features = ["full"], version = "0.1.24" }
serde = { features = ["derive"], version = "1.0.147" }
serde_json = "1.0.87"
sha2 = "0.10.6"
tokio = { features = ["full"], version = "1.21.2" }
tower = "0.4.13"
tower-http = "0.3.4"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
