[package]
authors = ["FL03 <jo3mccain@icloud.com>", "Scattered-Systems (https://scattered-systems.com)"]
categories = []
description = "Disarray core"
edition = "2021"
homepage = "https://github.com/scattered-systems/disarray"
keywords = []
license = "MIT"
name = "disarray-core"
readme = "README.md"
repository = "https://github.com/scattered-systems/disarray"
version = "0.1.7" # TODO - Update the cargo package version

[lib]
bench = false
crate-type = ["cdylib", "rlib"]
test = true

[dependencies]
bson = { features = ["chrono-0_4", "serde_with"], version = "2.3.0" }
chrono = "0.4.19"
config = "0.13.1"
digest = "0.10.3"
glob = "0.3.0"
http = "0.2.8"
hyper = { features = ["full"], version = "0.14.19" }
libp2p = { features = ["dns-tokio", "tcp-tokio", "wasm-bindgen"], version = "0.46.1" }
log = "0.4.17"
serde = { features = ["derive"], version = "1.0.138" }
serde_json = "1.0.82"
tokio = { features = ["full"], version = "1.19.2" }