name: Rust

env:
  CARGO_TERM_COLOR: always

on:
  push:
    branches: [ "main", "master", "prod" ]
    tags: [ "v*.*.*" ]
  schedule:
    - cron: "30 9 * * *"
  workflow_dispatch:
    inputs:
      publish:
        default: true
        description: 'Publish'
        required: true
        type: boolean

jobs:
  build:
    name: Build and Test
    strategy:
      matrix:
        toolchain: [ stable, nightly ]
        platform: [ macos-latest, ubuntu-latest, windows-latest ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo build -v
      - run: cargo test --all --all-features -v
  features:
    if: ${{ github.event.inputs.publish }}
    name: Features
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - disarray-core
          - disarray-ledger
          - disarray-minis
          - disarray-network
          - disarray-runtime
          - disarray-sdk
    steps:
      - uses: actions/checkout@v3
      - name: Publish (${{matrix.package}})
        run: cargo publish --all-features -v -p ${{ matrix.package }} --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
  sdk:
    if: ${{ github.event.inputs.publish }}
    name: Publish
    needs: features
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish (disarray-sdk)
        run: cargo publish --all-features -v -p disarray-sdk --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
  publish:
    if: ${{ github.event.inputs.publish }}
    name: Publish
    needs: [ features, sdk ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish (disarray)
        run: cargo publish --all-features -v -p disarray --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
