name: Rust

on:
  push:
    tags:
      - v*.*.*
  pull_request:
    tags:
      - v*.*.*

env:
  CARGO_TERM_COLOR: always

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login
        run: cargo login ${{ secrets.CARGO_REGISTRY_TOKEN }}
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: cargo test --quiet --release --workspace
  features:
    runs-on: ubuntu-latest
    needs: [ login, testing ]
    steps:
      - uses: actions/checkout@v3
      - name: Build and Push (derive)
        run: cargo publish --package disarray-core --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - name: Build and Push (derive)
        run: cargo publish --package disarray-derive --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - name: Build and Push (macros)
        run: cargo publish --package disarray-macros --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - name: Build and Push (network)
        run: cargo publish --package disarray-network --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
  crate:
    env:
      CRATE: disarray
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: [ features, login, testing ]
    steps:
      - uses: actions/checkout@v3
      - name: Login
        run: cargo login ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - name: Build and Push
        run: cargo publish --all-features --package $CRATE --token ${{ secrets.CARGO_REGISTRY_TOKEN }}