name: Rust

on:
  push:
    branches-ignore: [ "dev", "next" ]
    tags:
      - v*.*.*
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: sudo apt install -y protobuf-compiler
    - name: Build
      run: cargo build --release --verbose --workspace
    - name: Test
      run: cargo test --all-features --release --verbose
