name: Rust

on:
  push:
    branches:
      - master
    tags:
      - latest
  pull_request:
    branches:
      - master
    tags:
      - latest

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: cargo test --color $CARGO_TERM_COLOR --release --verbose --workspace
  core:
    env:
      CRATE: disarray-core
    runs-on: ubuntu-latest
    needs: [ test ]
    steps:
      - uses: actions/checkout@v3
      - name: Login
        run: cargo login ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - name: Build and Push
        run: cargo publish --package $CRATE --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
  derive:
    env:
      CRATE: disarray-derive
    runs-on: ubuntu-latest
    needs: [ test ]
    steps:
      - uses: actions/checkout@v3
      - name: Login
        run: cargo login ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - name: Build and Push
        run: cargo publish --package $CRATE --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
  macros:
    env:
      CRATE: disarray-macros
    runs-on: ubuntu-latest
    needs: [ test ]
    steps:
      - uses: actions/checkout@v3
      - name: Login
        run: cargo login ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - name: Build and Push
        run: cargo publish --package $CRATE --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
  network:
    env:
      CRATE: disarray-network
    runs-on: ubuntu-latest
    needs: [ test ]
    steps:
      - uses: actions/checkout@v3
      - name: Login
        run: cargo login ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - name: Build and Push
        run: cargo publish --package $CRATE --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
  crate:
    env:
      CRATE: disarray
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: [ core, derive, macros, network, test ]
    steps:
      - uses: actions/checkout@v3
      - name: Login
        run: cargo login ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - name: Build and Push
        run: cargo publish --all-features --package $CRATE --token ${{ secrets.CARGO_REGISTRY_TOKEN }}